### PR TITLE
Expenses test cases fix

### PR DESCRIPTION
**Pull request by ygarapati**
fixes in test cases of expenses module

### CODE REVIEW

**Review by Tanmayee17 — APPROVED** [review]
Excellent work on fixing the expenses test cases!. They are precise.

**Comment by PravarshaErodula6** [comment]
The fixes in the expenses module's test cases have been reviewed and are accurate.

**Review by PravarshaErodula6 — APPROVED** [review]
The fixes in the expenses module's test cases have been reviewed and are accurate.

**Comment by Gayatrinj** [comment]
test cases have been reviewed and approve . Great!

**Review by Gayatrinj — APPROVED** [review]

**Pull request merged**
