### PR TITLE
Expense category tanmayee

### PR DESCRIPTION
**Pull request by Tanmayee17**
I have changed a few categories in the category column that are unnecessary for the expense module and listed the necessary ones.

### CODE REVIEW

**Review by PravarshaErodula6 — APPROVED** [review]
All ok

**Comment by Gayatrinj** [comment]
Simplifying categories can make expense tracking more efficient and straightforward. Great!

**Review by Gayatrinj — APPROVED** [review]

**Comment by ygarapati** [comment]
please change franchising spelling in expenses/model.py Franchising

**Review by ygarapati — APPROVED** [review]

**Comment by Tanmayee17** [comment]
> please change franchising spelling in expenses/model.py Franchising

I just did, thankyou!

**Pull request merged**
